; PlatformIO Project Configuration File
; JCY8001 固件 - PlatformIO 移植版

[env:genericSTM32F103RC]
platform = ststm32
board = genericSTM32F103RC
framework = baremetal

; 调试信息
build_type = debug

; 上传配置
upload_protocol = jlink
; upload_port = /dev/ttyUSB0

; 编译选项
build_flags =
    -D USE_HSE_CLOCK
    -D HSE_VALUE=8000000
    -D STM32F1xx
    -D VECT_TAB_SRAM
    -Wl,--defsym=LoadAddr=0x08000000
    -Wl,--gc-sections

; 串口输出
monitor_speed = 115200
