; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103RC]
platform = ststm32
board = genericSTM32F103RC
framework = stm32cube
board_build.mcu = stm32f103rct6
board_build.f_cpu = 72000000L
debug_tool = jlink
upload_protocol = jlink
custom_freertos_config_location = lib/freertos/FreeRTOSConfig.h

build_flags =
	-DUSE_HAL_DRIVER
	-DSTM32F103xE
	-Os
	-I lib/modbus
	-I lib/drivers
	-I lib/freertos
	-I lib/dnb11xx
	-I lib/spi
	-I lib/eeprom
	-I include
monitor_speed = 115200
lib_deps =
	bblanchon/ArduinoJson@^7.4.3
	mincrmatt12/STM32Cube Middleware-FreeRTOS@10.3.1+f4-1.26.1
